// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "http://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/download": {
            "get": {
                "description": "Get download URL and metadata for a song or batch download from playlist/album",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "music"
                ],
                "summary": "Download music",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"2161154646\"",
                        "description": "Resource to download (song ID, album URL, playlist URL, song URL)",
                        "name": "resource",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "standard",
                            "higher",
                            "exhigh",
                            "lossless",
                            "hires",
                            "128",
                            "192",
                            "320",
                            "HQ",
                            "SQ",
                            "HR"
                        ],
                        "type": "string",
                        "example": "\"lossless\"",
                        "description": "Audio quality level",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"./downloads\"",
                        "description": "Output directory path",
                        "name": "output",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 30000,
                        "description": "Timeout in milliseconds",
                        "name": "timeout",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BatchDownloadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the current health status of the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HealthResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticates user with provided credentials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/process": {
            "post": {
                "description": "Processes input data and returns the result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Process data",
                "parameters": [
                    {
                        "description": "Data to process",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ProcessRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ProcessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BatchDownloadResponse": {
            "description": "Batch music download response",
            "type": "object",
            "properties": {
                "failed": {
                    "type": "integer",
                    "example": 2
                },
                "message": {
                    "type": "string",
                    "example": "Batch download completed"
                },
                "songs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DownloadResponse"
                    }
                },
                "success": {
                    "type": "integer",
                    "example": 8
                },
                "total": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "models.DownloadResponse": {
            "description": "Music download response",
            "type": "object",
            "properties": {
                "album": {
                    "type": "string",
                    "example": "Album Name"
                },
                "album_pic_url": {
                    "type": "string",
                    "example": "https://..."
                },
                "artist": {
                    "type": "string",
                    "example": "Artist Name"
                },
                "download_url": {
                    "type": "string",
                    "example": "https://..."
                },
                "downloaded_path": {
                    "type": "string",
                    "example": "./downloads/Song Title.flac"
                },
                "duration": {
                    "type": "integer",
                    "example": 240000
                },
                "file_size": {
                    "type": "integer",
                    "example": 15728640
                },
                "file_type": {
                    "type": "string",
                    "example": "flac"
                },
                "message": {
                    "type": "string",
                    "example": "Download URL generated successfully"
                },
                "quality": {
                    "type": "string",
                    "example": "lossless"
                },
                "song_id": {
                    "type": "string",
                    "example": "2161154646"
                },
                "song_name": {
                    "type": "string",
                    "example": "Song Title"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.ErrorResponse": {
            "description": "Error response",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid input"
                }
            }
        },
        "models.HealthResponse": {
            "description": "Health check response",
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string",
                    "example": "development"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "models.LoginRequest": {
            "description": "User login request",
            "type": "object",
            "required": [
                "password",
                "uuid"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "server": {
                    "type": "string",
                    "example": "netease"
                },
                "timeout": {
                    "type": "integer",
                    "example": 30000
                },
                "uuid": {
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "models.LoginResponse": {
            "description": "User login response",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Login successful"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "user_id": {
                    "type": "integer",
                    "example": 123456789
                },
                "username": {
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "models.ProcessRequest": {
            "description": "Data processing request",
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "type": "string",
                    "example": "hello world"
                }
            }
        },
        "models.ProcessResponse": {
            "description": "Data processing response",
            "type": "object",
            "properties": {
                "result": {
                    "type": "string",
                    "example": "processed: hello world"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Miko Service API",
	Description:      "A Go service library with HTTP API endpoints",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
